version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:      
      - aws s3 sync ./build s3://yapa-ui/static --exclude "*" --include "index.html" --metadata-directive REPLACE --cache-control "no-cache";      
      #- >
      #  aws s3 sync ./build s3://yapa-ui/static 
      #  --exclude "*" --include "config.json" 
      # --metadata-directive REPLACE --cache-control "max-age=900,public" --content-type "application/json"      
      - >
        aws s3 sync ./build s3://yapa-ui/static 
        --exclude "index.html" --exclude "node_modules/*"
        --metadata-directive REPLACE --cache-control "max-age=2592000,public"
      
      - >
        aws cloudfront create-invalidation --paths /index.html
artifacts:
  files:
    - '**/*'
  base-directory: build