
export const GET_MAIN_CATEGORIES = 'app/ExpenseDialog/GET_MAIN_CATEGORIES';
export const GET_MAIN_CATEGORIES_SUCCESS = 'app/ExpenseDialog/GET_MAIN_CATEGORIES_SUCCESS';
export const GET_MAIN_CATEGORIES_ERROR = 'app/ExpenseDialog/GET_MAIN_CATEGORIES_ERROR';
export const GET_SUB_CATEGORIES = 'app/ExpenseDialog/GET_SUB_CATEGORIES';
export const GET_SUB_CATEGORIES_SUCCESS = 'app/ExpenseDialog/GET_SUB_CATEGORIES_SUCCESS';
export const GET_SUB_CATEGORIES_ERROR = 'app/ExpenseDialog/GET_SUB_CATEGORIES_ERROR';
export const SELECT_MAIN_CATEGORY = 'app/ExpenseDialog/SELECT_MAIN_CATEGORY';
export const SELECT_SUB_CATEGORY = 'app/ExpenseDialog/SELECT_SUB_CATEGORY';
export const SELECT_PRICE = 'app/ExpenseDialog/SELECT_PRICE';
export const SELECT_EXPENSE_TYPE = 'app/ExpenseDialog/SELECT_EXPENSE_TYPE';
export const SET_SPENT_AT = 'app/ExpenseDialog/SET_SPENT_AT';
export const SET_DESCRIPTION = 'app/ExpenseDialog/SET_DESCRIPTION';
export const ADD_EXPENSE = 'app/ExpenseDialog/ADD_EXPENSE';
export const ADD_EXPENSE_SUCCESS = 'app/ExpenseDialog/ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_ERROR = 'app/ExpenseDialog/ADD_EXPENSE_ERROR';
export const RESET_EXPENSE_DIALOG = 'app/ExpenseDialog/RESET_EXPENSE_DIALOG';

export default {
    GET_MAIN_CATEGORIES,
    GET_MAIN_CATEGORIES_SUCCESS,
    GET_MAIN_CATEGORIES_ERROR,
    GET_SUB_CATEGORIES,
    GET_SUB_CATEGORIES_SUCCESS,
    GET_SUB_CATEGORIES_ERROR,
    SELECT_MAIN_CATEGORY,
    SELECT_SUB_CATEGORY,
    SELECT_PRICE,
    SELECT_EXPENSE_TYPE,
    SET_SPENT_AT,
    SET_DESCRIPTION,
    ADD_EXPENSE,
    ADD_EXPENSE_SUCCESS,
    ADD_EXPENSE_ERROR,
    RESET_EXPENSE_DIALOG
}
