
export const OPEN_ADD_EXPENSE_FORM = 'yapaui/HomePage/OPEN_ADD_EXPENSE_FORM';
export const CLOSE_EXPENSE_FORM = 'yapaui/HomePage/CLOSE_EXPENSE_FORM';
export const ADD_EXPENSE = 'yapaui/HomePage/ADD_EXPENSE';
export const ADD_EXPENSE_SUCCESS = 'yapaui/HomePage/ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_ERROR = 'yapaui/HomePage/ADD_EXPENSE_ERROR';

export default {
	OPEN_ADD_EXPENSE_FORM,
	CLOSE_EXPENSE_FORM,
	ADD_EXPENSE,
	ADD_EXPENSE_SUCCESS,
	ADD_EXPENSE_ERROR
};