
export const OPEN_ADD_EXPENSE_FORM = 'yapaui/HomePage/OPEN_ADD_EXPENSE_FORM';
export const CLOSE_EXPENSE_FORM = 'yapaui/HomePage/CLOSE_EXPENSE_FORM';
export const GET_EXPENSES = 'yapaui/HomePage/GET_EXPENSES';
export const GET_EXPENSES_SUCCESS = 'yapaui/HomePage/GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_ERROR = 'yapaui/HomePage/GET_EXPENSES_ERROR';

export default {
	OPEN_ADD_EXPENSE_FORM,
	CLOSE_EXPENSE_FORM,
	GET_EXPENSES,
	GET_EXPENSES_SUCCESS,
	GET_EXPENSES_ERROR
};